### ISSUE TITLE
Questions on auto optimization of regularization parameter

### ISSUE THREAD

**Issue by jianzuo** [leehangyue/EISART#1]
Hi,
Thanks for providing such a great tool.
After some experiment, I have encounted a problem on regularization parameter (lambda) optimization.

- What are the method used in EISart to optimize lambda?
- There is a **Auto lambda** in the GUI pannel. When selecting this, how do we know the value of the optimized 
lambda?
- When selecting Auto lambda, why does the DRT results are still changed when setting different **Lambda** values in the pannel?

Thank you very much!

**Comment by leehangyue** [comment]
Thanks for your interest!

- EISART uses an open-loop method to determine the distribution of lambda, in order to balance between DRT variation and resolution. If "Auto Lambda" is checked, lambda increases from the set value where EIS fitting residuals are larger. If "Auto Lambda" is not checked, lambda is a user-specified constant.

- "Auto Lambda" does not change the overall lambda, but changes the distribution of lambda over relaxation time, hence the value of lambda is not unique. You may add a break point in debug mode on line 831 in util_tikhonov.py to inspect the values of lambda (lmd_vector).

- Because the user-specified set value of lambda is the starting point of auto adjustments.

If you have any further question, please feel free to leave another comment ;-)

**Comment by jianzuo** [comment]
Hi,
Thank you very much for the explanation, it is clear now, I will try to explore more based on this.
Recently, I am using your tool in my work, I am trying to put together a couple of questions (may related to better understanding the use of this tool),  and I will leave them in the next issue discussion. 
Thanks again for your time!

**Comment by jianzuo** [comment]
Currently, I am more interested in the DRT results (the time constant and polarization resistance from measured EIS spectra).
- I also tried the well-known DRTtools from Ciuccis et al. Does EISart share similar regularization method for calculating DRT? 
- In EISart, if the auto lambda if not selected in the GUI, it seems the regularization part only has one, i.e. lambda parameter to be tuned? While in DRTtools, there is, for example, FWHM coefficient to be tuned. 
- Can you give some hints on what are the important parameters to be tunned when compute DRT from measured EIS?
Thank you very much!
