### ISSUE TITLE
Questions regarding DRT calculation

### ISSUE THREAD

**Issue by jianzuo** [leehangyue/EISART#2]
Currently my primary focus is to improve the accuracy of DRT calculation results, i.e., $\gamma(\ln\tau)$. I am a little confused:
- What is the accessible criteria for comparing the DRT calculation accuracy over different parameter setting? 
- In the provided GUI, there is `Fitting residual from Input', what does this residual mean?  Is this for estimating the accuracy of the ECM?
- What does the `Input' in the GUI pannal mean? For the four figures in the GUI, three of them have this Input, the Input in the Nyquist and Bode figures mean the data from the measured EIS, I think. What does the **Input in the DRT figure** mean? 
- It seems that EISart did support to **export the polarization resistance** (area under each peak) of the identified peaks **from DRT** (not from the estimated ECM)? 

Thank you!

**Comment by leehangyue** [comment]
thx for your interest.

- In EISART, the accuracy of DRT is calculated as the weighted RMS error between the input EIS and the regenerated EIS from DRT. This is the fitting error printed to the terminal. No direct DRT error is computed in EISART, since there is no reliable reference DRT for each input EIS. 
- The fitting residual from input means the weighted RMS error between the input EIS and the regenerated EIS from ECM. It is for estimating the accuracy of the ECM.
- Input in the left part of the GUI means the options related to the input EIS files. Input in the right part (figures) of the GUI means the either the input EIS data or the DRT calculated from the input EIS.
- The exported resistances comprise the resistance of each RQ element in ECM, while the area under peaks are only the initial guesses for ECM parameter refinement.

If you have any further questions, please feel free to ask ;-)
